import pandas as pd

def generate_responses(mentee_directory, mentor_directory):
  """
  This function takes a directory of mentees and a directory of mentors 
  and returns a csv of matching form responses. The schema for the matching
  form can be found in DOCS.md
  """

  # First 5 columns are autogenerated by Microsoft Forms so can be filler values
  matching_form_schema = {
        'Id': [],
        'Start time': [],
        'Completion time': [],
        'Email': [],
        'Name': [],
        'KIN Mentorship ID (Link to Spreadsheet)': [], 
        'First Name': [],
        'Last Name': [],
        'Email Address': [],
        'Please indicate if you have a preference for what gender your mentor/mentee is:': [],
        'How important is accessing and developing a professional AAPI network?': [],
        'How open are you to exploring topics outside of your immediate career or academic focus in the mentorship?': [],
        'How much do you value a structured mentoring relationship (e.g., goal setting, progress tracking)?': [],
        'How important is frequent communication (e.g., weekly or bi-weekly) in a mentoring relationship?': [],
        'Select if you are a Kin Mentor or Kin Mentee': [],
        'Would you be open to the possibility of having 2 Kin Mentees?': [],
        'What industries can you provide mentorship on?': [],
        'How comfortable do you feel providing guidance on professional skills such as resume writing, interviewing, personal brand, presentation skills, etc.?': [],
        'How confident do you feel in guiding your mentee in securing an internship or full-time employment opportunity?': [],
        'Who is your #1 Kin Mentee preference?': [],
        'Who is your #2 Kin Mentee preference?': [],
        'Who is your #3 Kin Mentee preference?': [],
        'Who is your #4 Kin Mentee preference?': [],
        'Who is your #5 Kin Mentee preference?': [],
        'Who is your #6 Kin Mentee preference?': [],
        'Who is your #7 Kin Mentee preference?': [],
        'Who is your #8 Kin Mentee preference?': [],
        'Who is your #9 Kin Mentee preference?': [],
        'Who is your #10 Kin Mentee preference?': [],
        'Who is your #11 Kin Mentee preference?': [],
        'Who is your #12 Kin Mentee preference?': [],
        'Who is your #13 Kin Mentee preference?': [],
        'Who is your #14 Kin Mentee preference?': [],
        'Who is your #15 Kin Mentee preference?': [],
        'Would you be open to the possibility of having a 1 Kin Mentor: 2 Kin Mentee mentorship partnership?': [],
        'What industries are you interested in receiving mentorship on?': [],
        'How important is enhancing professional skills (resume writing, interviewing, personal brand, presentation skills, etc.)?': [],
        'How important is securing an internship or full-time employment opportunity?': [],
        'Who is your #1 Kin Mentor preference?': [],
        'Who is your #2 Kin Mentor preference?': [],
        'Who is your #3 Kin Mentor preference?': [],
        'Who is your #4 Kin Mentor preference?': [],
        'Who is your #5 Kin Mentor preference?': [],
        'Who is your #6 Kin Mentor preference?': [],
        'Who is your #7 Kin Mentor preference?': [],
        'Who is your #8 Kin Mentor preference?': [],
        'Who is your #9 Kin Mentor preference?': [],
        'Who is your #10 Kin Mentor preference?': [],
        'Who is your #11 Kin Mentor preference?': [],
        'Who is your #12 Kin Mentor preference?': [],
        'Who is your #13 Kin Mentor preference?': [],
        'Who is your #14 Kin Mentor preference?': [],
        'Who is your #15 Kin Mentor preference?': [],
        'How comfortable do you feel in asking for help in achieving your academic and career goals?': [],
        'How prepared do you feel to take the next steps in your career?': [],
        'How connected do you feel to a network of professionals to achieve your academic and career goals?': [],
        'As an AAPI student, how empowered (supported and confident) do you feel in your ability to achieve your career goals?': [],
        'How connected do you feel to the AAPI community?': [],
        'Is there anything else that you would like us to consider as part of the matching process?': []
    }

  df = pd.DataFrame(matching_form_schema)
  return df

def generate_mentor_response():
  pass

def generate_mentee_response():
  pass

generate_responses("mentee_directory", "mentor_directory")