"""
This module will process the raw form response data into
a format that can be used in the Gale-Shapley algorithm.
Form Schema can be found here:
https://docs.google.com/spreadsheets/d/1RpGKGtm9DIUIlmZmTEvZTqQ3wwXW3MMJ/edit?gid=855474137#gid=855474137
"""

import pandas as pd
import numpy as np

def process_form_data(form_data):
    """
    Process the raw form data into a format that can be used in the Gale-Shapley algorithm.
    """
    # Load the form data into a pandas dataframe
    df = pd.read_csv(form_data)

    # Drop the metadata columns generated by Microsoft Forms
    df = df.drop(columns=['Id','Start time','Completion time','Email', 'Name'])

    # TODO: Rename the columns - what is the best naming convention

    df.to_csv("processed_data.csv", index=False)

if __name__ == "__main__":
    process_form_data("matching_responses.csv")