"""
This module will process the raw form response data into
a format that can be used in the Gale-Shapley algorithm.
Form Schema can be found here:
https://docs.google.com/spreadsheets/d/1RpGKGtm9DIUIlmZmTEvZTqQ3wwXW3MMJ/edit?gid=855474137#gid=855474137
"""

import pandas as pd
import numpy as np

def process_form_data(form_data):
    """
    Process the raw form data into a format that can be used in the Gale-Shapley algorithm.
    """
    # Load the form data into a pandas dataframe
    df = pd.read_csv(form_data)

    # Drop the metadata columns generated by Microsoft Forms (first 5 columns) and 
    # Drop the data collection questions (last 6 columns)
    df = df.drop(df.columns[:5].tolist() + df.columns[-6:].tolist(), axis=1)

    # Can drop names and emails since they are not needed for the algorithm
    df = df.drop(["First Name", "Last Name", "Email Address"], axis=1)

    

    df.to_csv("processed_data.csv", index=False)

if __name__ == "__main__":
    process_form_data("matching_responses.csv")