"""
This module will process the raw form response data into
a format that can be used in the Gale-Shapley algorithm.
Form Schema can be found here:
https://docs.google.com/spreadsheets/d/1RpGKGtm9DIUIlmZmTEvZTqQ3wwXW3MMJ/edit?gid=855474137#gid=855474137
"""

import pandas as pd
import numpy as np

def process_form_data(form_data):
    """
    Process the raw form data into a format that can be used in the Gale-Shapley algorithm.
    """
    # Load the form data into a pandas dataframe
    df = pd.read_csv(form_data)

    # Drop the metadata columns generated by Microsoft Forms (first 5 columns) and 
    # Drop the data collection questions (last 6 columns)
    df = df.drop(df.columns[:5].tolist() + df.columns[-6:].tolist(), axis=1)

    # # Can drop names and emails since they are not needed for the algorithm
    df = df.drop(["First Name", "Last Name", "Email Address"], axis=1)

    # TODO: Replace NaN values with 0? How can we factor them out so they have minimal impact on the algorithm?

    # Rename the first column to "Participant" by index
    df.columns.values[0] = "ID"
    df.columns.values[1] = "gender"
    df.columns.values[2] = "Rank 1"
    df.columns.values[3] = "Rank 2"
    df.columns.values[4] = "Rank 3"
    df.columns.values[5] = "Rank 4"
    df.columns.values[6] = "Mentor or Mentee?"
    
    for row in df.iterrows():
        pass

    df.to_csv("processed_data.csv", index=False)

if __name__ == "__main__":
    process_form_data("matching_responses.csv")