import pytest
from .generate_matching_responses import generate_responses, read_directory

def test_generate_matching_responses_shape():
    # There are 54 questions in the form, and 5 additional columns generated by Microsoft  forms
    mentee_directory = read_directory("mentee_directory_15.csv")
    mentor_directory = read_directory("mentor_directory_15.csv")
    df = generate_responses(mentee_directory, mentor_directory)
    assert df.shape[1] == 59, f"Expected 59 columns, but got {df.shape[1]}"

def test_read_diretory():
  directory = read_directory("mentee_directory_15.csv")
  assert(len(directory) == 15), f"Expected 15 rows, but got {len(read_directory)}"

if __name__ == "__main__":
    pytest.main()