import pytest
from pathlib import Path
from src.generate_matching_responses import generate_responses, read_directory

data_dir = Path(__file__).resolve().parent.parent / "data"


def test_generate_matching_responses_shape():
    # There are 54 questions in the form, and 5 additional columns generated by Microsoft  forms
    mentee_directory = read_directory(data_dir / "mentee_directory_200.csv")
    mentor_directory = read_directory(data_dir / "mentor_directory_200.csv")
    df = generate_responses(mentee_directory, mentor_directory)
    assert df.shape[1] == 60, f"Expected 60 columns, but got {df.shape[1]}"
    assert df.shape[0] == 400, f"Expected 400 rows, but got {df.shape[0]}"


def test_read_diretory():
    directory = read_directory(data_dir / "mentee_directory_200.csv")
    assert len(directory) == 200, f"Expected 200 rows, but got {len(read_directory)}"


if __name__ == "__main__":
    pytest.main()
